version: '2'
services: 
    neo4j:
        container_name: neo4j
        image: neo4j:3.1.0        
        networks: 
            - app-maisvida
        env_file: variables.env
        ports:
            - "7474:7474"
            - "7687:7687"
networks:
    app-maisvida: